import os
SQLALCHEMY_DATABASE_URI=os.environ.get('SQLALCHEMY_DATABASE_URI')
SECRET_KEY=os.environ.get('SECRET_KEY')
SQLALCHEMY_TRACK_MODIFICATIONS=False
RECAPTCHA_PUBLIC_KEY=os.environ.get('RECAPCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY=os.environ.get('RECAPCHA_PRIVATE_KEY')
VERIFY_URL=os.environ.get("VERIFY_URL")
