"""added the colum country in table users

Revision ID: c58f9d1c997e
Revises: e4e4e91491c6
Create Date: 2021-04-05 20:22:15.851565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58f9d1c997e'
down_revision = 'e4e4e91491c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'country')
    # ### end Alembic commands ###
