"""empty message

Revision ID: 39bb7ef28bd5
Revises: 755f5ab5afbe
Create Date: 2021-04-21 20:11:16.832419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39bb7ef28bd5'
down_revision = '755f5ab5afbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('randoms', schema=None) as batch_op:
        batch_op.drop_column('param2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('randoms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('param2', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
