"""empty message

Revision ID: 4ed07ad8e833
Revises: ad7dcac8bb54
Create Date: 2021-04-26 20:00:36.201845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed07ad8e833'
down_revision = 'ad7dcac8bb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.Unicode(length=255), server_default='', nullable=False))
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), server_default=sa.text("('')"), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_unique_constraint('uq_users_username', ['username'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###
