"""empty message

Revision ID: a99faa0cc155
Revises: 4a907061bba7
Create Date: 2021-04-23 21:15:51.931598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99faa0cc155'
down_revision = '4a907061bba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255, collation='NOCASE'), nullable=False))
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###
