"""empty message

Revision ID: f4b9619f0347
Revises: fcc74a19d38c
Create Date: 2021-04-21 20:14:07.893146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b9619f0347'
down_revision = 'fcc74a19d38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('randoms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('param2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('param3', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('randoms', schema=None) as batch_op:
        batch_op.drop_column('param3')
        batch_op.drop_column('param2')

    # ### end Alembic commands ###
