"""added about field to User

Revision ID: 85aa98a75371
Revises: ef944b4ff646
Create Date: 2022-07-28 19:27:09.579586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85aa98a75371'
down_revision = 'ef944b4ff646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about')
    # ### end Alembic commands ###
