"""empty message

Revision ID: 59d2c227fce9
Revises: 2e2a84e2a34a
Create Date: 2021-04-11 10:02:19.585202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d2c227fce9'
down_revision = '2e2a84e2a34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
