"""test on  adding a column

Revision ID: 931bfbc441b8
Revises: cc36aa313b43
Create Date: 2021-04-11 10:22:59.113149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931bfbc441b8'
down_revision = 'cc36aa313b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_column', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test_column')

    # ### end Alembic commands ###
