"""empty message

Revision ID: cc36aa313b43
Revises: 639a73ead281
Create Date: 2021-04-11 10:22:29.831714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc36aa313b43'
down_revision = '639a73ead281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
