"""empty message

Revision ID: 639a73ead281
Revises: 6da3a8a7c03a
Create Date: 2021-04-11 10:06:10.854062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639a73ead281'
down_revision = '6da3a8a7c03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
